---
title: "A gentle tutorial of accelerated parameter and confidence interval estimation for Hidden Markov Models using Template Model Builder"
output:  github_document
---

<!-- # A gentle tutorial of accelerated parameter and confidence interval estimation for Hidden Markov Models using Template Model Builder -->

<!-- Compile this into README.md with -->
<!-- rmarkdown::render("README.Rmd", md_document()) -->

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::knit_engines$set()
```
*Contributors: Timothee Bacri<sup>1</sup>, Geir Drage Berentsen<sup>2</sup>, Jan Bulla<sup>1</sup> and Sondre Hølleland<sup>3</sup>.*

1) *University of Bergen, Norway.*
2) *Norwegian Buisness school, Norway.*
3) *Institute of Marine Research, Norway.*

  *Correspondance to: jan.bulla@uib.no*
 
 *Biometrical Journal paper can be found [here (correct link will come)](https://onlinelibrary.wiley.com/journal/15214036).*

This repository contains the code to produce the R-bookdown website found [here](https://timothee-bacri.github.io/HMM_with_TMB/).

The folders (*[code/](#code)*, *[data/](#data)*, *[functions/](#functions)*) related to the analysis code and results of the paper [LINK available later](https://www.nrk.no) are described in [Directory structure](#directory-structure).

## Author's github account

**Timothee Bacri** - [timothee-bacri](https://github.com/timothee-bacri)

**Sondre Hølleland** - [holleland](https://github.com/holleland)

## License

[ UNDER CONSTRUCTION ] \
This project is licensed under the GPL v2 License - see [LICENSE](LICENSE) for details.
